-- 0041 — The enrolment lifecycle: events, transfers, withdrawals.
--
-- Phase 0 found `public.enrollment_events` seeded into the schema by
-- migration 0005 with RLS, grants and a foreign key — and NEVER WRITTEN
-- TO. Zero rows, no code path, in any migration or screen. The same was
-- true of `class_enrollments.status` and `.date_dropped`.
--
-- Both are exactly the mechanism this phase needs, which is the fourth
-- time in this build that the structure for a feature turned out to be
-- already there. Nothing new is created here that the schema could
-- already express.
--
-- ── WHY THE EVENT LOG IS NOT THE AUDIT LOG ────────────────────────────
--
-- `audit_logs` already records every write, and `update_enrollment`
-- already writes to it. So why a second table?
--
-- Because they answer different questions and have different lifetimes.
-- The audit log answers "who changed this row and when", is written for
-- an investigator, and may be pruned. `enrollment_events` answers
-- "where was this learner during this school year", is READ BY SF10,
-- and must outlive any retention policy applied to the audit trail.
-- Deriving one from the other would mean parsing jsonb diffs years
-- later to reconstruct a transfer date — which is not a record, it is
-- an archaeology project.
--
-- Both are written. The event is the record; the audit row is the
-- accountability. Neither replaces the other.
--
-- ── WHAT A SECTION TRANSFER ACTUALLY HAS TO DO ────────────────────────
--
-- This is the part that would have silently corrupted rosters.
--
-- `sync_class_roster` (0010) ADDS every learner in a section to a class
-- and never removes anyone. Moving `enrollments.section_id` from Pearl
-- to Ruby therefore left the learner sitting in every one of Pearl's
-- class rosters — with their marks — while Ruby's classes never gained
-- them at all. The registrar's screen would say Ruby; four teachers
-- would still see them in Pearl.
--
-- The fix was already in the schema. Every roster and gradebook read in
-- the system filters `ce.status = 'active'` — verified across 28 call
-- sites — and nothing has ever set that column to anything else. So a
-- transfer:
--
--   1. marks the OLD section's class enrolments 'transferred', with a
--      date_dropped. Their assessment_scores are untouched: the score
--      rows point at class_enrollment_id, so every mark the learner
--      earned in Pearl survives exactly as recorded.
--   2. syncs every class in the NEW section, which adds them.
--
-- HISTORY IS NEVER DELETED. A transferred learner's marks stay readable
-- through the class they were earned in; they simply stop appearing on
-- a roster of people currently in the room.

begin;

-- ------------------------------------------------------------
-- 1. The event vocabulary
-- ------------------------------------------------------------
-- 0005 allowed transfer_in / transfer_out / drop / re_entry /
-- section_change. Two are missing for the lifecycle this phase builds:
-- the first enrolment itself, and a grade-level correction. Widened
-- additively — every existing value stays legal.
alter table public.enrollment_events
  drop constraint if exists enrollment_events_event_type_check;
alter table public.enrollment_events
  add constraint enrollment_events_event_type_check
  check (event_type in ('enrolled','transfer_in','transfer_out','drop',
                        're_entry','section_change','grade_level_change'));

-- from_value/to_value are text because the history has to stay readable
-- after the section is renamed or deleted — "Pearl" is what the record
-- must say in 2031. But a report also needs to JOIN, so keep the ids
-- alongside the names rather than choosing between them.
alter table public.enrollment_events add column if not exists from_ref uuid;
alter table public.enrollment_events add column if not exists to_ref   uuid;

-- ── WHY created_at IS NOT ENOUGH TO ORDER BY ─────────────────────────
--
-- `now()` is TRANSACTION time, not statement time. `enrol_student`
-- writes two events — the enrolment and the section assignment — in one
-- transaction, so both carry the identical created_at AND the identical
-- event_date. Ordering by those alone leaves the pair in whatever order
-- the plan happens to produce, and a history that says "assigned to
-- Pearl" above "enrolled" reads as nonsense.
--
-- Found by an ordering assertion, not by reading the code: it only
-- shows up when two events land in one statement.
alter table public.enrollment_events
  add column if not exists seq bigint generated by default as identity;

comment on table public.enrollment_events is
  'Where a learner was, and when they moved. Read by SF10. Distinct '
  'from audit_logs: this is the academic record, that is the '
  'accountability trail, and they have different lifetimes.';

create index if not exists enrollment_events_enrollment_idx
  on public.enrollment_events (school_id, enrollment_id, event_date, seq);

-- ------------------------------------------------------------
-- 2. app.record_enrollment_event — one writer, so the shape is uniform
-- ------------------------------------------------------------
create or replace function app.record_enrollment_event(
  p_enrollment_id uuid,
  p_event_type    text,
  p_event_date    date,
  p_from_value    text default null,
  p_to_value      text default null,
  p_from_ref      uuid default null,
  p_to_ref        uuid default null,
  p_notes         text default null
) returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_school uuid := app.current_school_id();
  v_id     uuid;
begin
  -- The enrolment must be this school's. Called only from RPCs that
  -- have already checked, but a helper that trusts its caller is a
  -- helper waiting to be called from somewhere that has not.
  if not exists (select 1 from public.enrollments e
                 where e.id = p_enrollment_id and e.school_id = v_school) then
    raise exception 'enrolment not found' using errcode = 'P0002';
  end if;

  insert into public.enrollment_events (
    school_id, enrollment_id, event_type, event_date,
    from_value, to_value, from_ref, to_ref, notes, recorded_by
  ) values (
    v_school, p_enrollment_id, p_event_type, coalesce(p_event_date, current_date),
    p_from_value, p_to_value, p_from_ref, p_to_ref,
    nullif(btrim(coalesce(p_notes, '')), ''), app.current_user_id()
  )
  returning id into v_id;

  return v_id;
end;
$fn$;

comment on function app.record_enrollment_event is
  'The only writer of enrollment_events, so every event has the same '
  'shape: what changed, from what, to what, by whom, when.';

-- ------------------------------------------------------------
-- 3. app.drop_class_enrolments — the inverse of sync_class_roster
-- ------------------------------------------------------------
-- Marks, never deletes. `assessment_scores.class_enrollment_id` points
-- at these rows; deleting one would take a term of marks with it.
create or replace function app.drop_class_enrolments(
  p_enrollment_id uuid,
  p_section_id    uuid,     -- null = every class, whatever the section
  p_status        text,     -- 'transferred' or 'dropped'
  p_effective     date
) returns int
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare v_n int;
begin
  with touched as (
    update public.class_enrollments ce
       set status = p_status,
           date_dropped = coalesce(p_effective, current_date)
      from public.classes cl
     where cl.id = ce.class_id
       and ce.enrollment_id = p_enrollment_id
       and ce.school_id = app.current_school_id()
       and ce.status = 'active'
       and (p_section_id is null or cl.section_id = p_section_id)
    returning 1
  )
  select count(*) into v_n from touched;
  return v_n;
end;
$fn$;

-- ------------------------------------------------------------
-- 3b. app.reactivate_class_enrolments — bringing a learner back
-- ------------------------------------------------------------
-- `class_enrollments` is UNIQUE (class_id, enrollment_id), so a learner
-- who left a class already HAS a row in it — closed. `sync_class_roster`
-- inserts `on conflict do nothing`, which means it silently skips them:
-- a re-enrolled learner rejoined nothing and their teacher's roster
-- stayed empty of them. Caught by running the withdraw → re-enrol path
-- rather than by reading the code, which is the only way this shows up.
--
-- Reactivating the existing row is also the only correct answer, not
-- merely the working one: `assessment_scores.class_enrollment_id`
-- points at that row, so a second row would orphan every mark the
-- learner earned before they left.
create or replace function app.reactivate_class_enrolments(
  p_enrollment_id uuid,
  p_section_id    uuid
) returns int
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare v_n int;
begin
  with touched as (
    update public.class_enrollments ce
       set status = 'active', date_dropped = null
      from public.classes cl
     where cl.id = ce.class_id
       and ce.enrollment_id = p_enrollment_id
       and ce.school_id = app.current_school_id()
       and ce.status <> 'active'
       and (p_section_id is null or cl.section_id = p_section_id)
       and cl.status = 'active'
    returning 1
  )
  select count(*) into v_n from touched;
  return v_n;
end;
$fn$;

-- ------------------------------------------------------------
-- 4. public.transfer_student_section
-- ------------------------------------------------------------
create or replace function public.transfer_student_section(
  p_enrollment_id uuid,
  p_section_id    uuid,
  p_effective_date date default null,
  p_reason        text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_school   uuid := app.current_school_id();
  v_e        public.enrollments;
  v_from     text;
  v_to       text;
  v_eff      date := coalesce(p_effective_date, current_date);
  v_dropped  int  := 0;
  v_added    int  := 0;
  v_class    uuid;
begin
  if not app.has_permission('enrollments.write') then
    raise exception 'not permitted to transfer a learner' using errcode = '42501';
  end if;
  if p_section_id is null then
    raise exception 'A section to move into is required.' using errcode = '23514';
  end if;

  select * into v_e from public.enrollments e
   where e.id = p_enrollment_id and e.school_id = v_school;
  if v_e.id is null then
    raise exception 'enrolment not found' using errcode = 'P0002';
  end if;

  -- The destination must be this school's, in the SAME academic year,
  -- and at the SAME grade level. A section is a grade level and a name;
  -- moving a Grade 10 learner into a Grade 7 section is not a transfer,
  -- it is a grade-level change, and it should be refused rather than
  -- silently performed as a side effect.
  select sec.name into v_to
  from public.sections sec
  where sec.id = p_section_id
    and sec.school_id = v_school
    and sec.academic_year_id = v_e.academic_year_id
    and sec.grade_level_id = v_e.grade_level_id;

  if v_to is null then
    raise exception
      'That section is not available for this learner''s year and grade level.'
      using errcode = '23503';
  end if;

  if v_e.section_id = p_section_id then
    raise exception 'This learner is already in %.', v_to using errcode = '23505';
  end if;

  select sec.name into v_from from public.sections sec where sec.id = v_e.section_id;

  -- 1. leave the old section's classes, keeping every mark
  if v_e.section_id is not null then
    v_dropped := app.drop_class_enrolments(
      p_enrollment_id, v_e.section_id, 'transferred', v_eff);
  end if;

  -- 2. move
  update public.enrollments
     set section_id = p_section_id, updated_at = now()
   where id = p_enrollment_id;

  -- 3. join the new section's classes. Reactivate before syncing, for
  --    the learner moved to Diamond and back to Pearl: their Pearl rows
  --    are closed, not absent, and sync_class_roster's `on conflict do
  --    nothing` would skip them — leaving a learner who is in Pearl
  --    according to the registrar and on nobody's roster.
  v_added := app.reactivate_class_enrolments(p_enrollment_id, p_section_id);
  for v_class in
    select cl.id from public.classes cl
    where cl.school_id = v_school
      and cl.section_id = p_section_id
      and cl.academic_year_id = v_e.academic_year_id
      and cl.status = 'active'
  loop
    v_added := v_added + coalesce(public.sync_class_roster(v_class), 0);
  end loop;

  -- An assignment and a transfer are the same EVENT TYPE with a
  -- different from_value: null means the learner had no section, which
  -- reads correctly as "assigned to Pearl" rather than "moved to Pearl".
  perform app.record_enrollment_event(
    p_enrollment_id, 'section_change',
    v_eff, v_from, v_to, v_e.section_id, p_section_id, p_reason);

  perform app.write_audit('enrollments.transfer_section', 'enrollments',
    p_enrollment_id,
    jsonb_build_object('sectionId', v_e.section_id, 'section', v_from),
    jsonb_build_object('sectionId', p_section_id, 'section', v_to,
                       'effectiveDate', v_eff),
    p_reason);

  return jsonb_build_object(
    'from', v_from, 'to', v_to,
    'classesLeft', v_dropped, 'classesJoined', v_added);
end;
$fn$;

comment on function public.transfer_student_section is
  'Moves a learner to another section in the same year and grade level. '
  'Their old class enrolments are marked transferred, never deleted — '
  'every mark earned in the previous section stays exactly as recorded.';

-- ------------------------------------------------------------
-- 5. public.withdraw_student — transferred out, or dropped
-- ------------------------------------------------------------
create or replace function public.withdraw_student(
  p_enrollment_id  uuid,
  p_kind           text,              -- 'transferred_out' | 'dropped'
  p_effective_date date default null,
  p_reason         text default null,
  p_destination    text default null  -- the receiving school, if known
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_school  uuid := app.current_school_id();
  v_e       public.enrollments;
  v_eff     date := coalesce(p_effective_date, current_date);
  v_n       int;
begin
  if not app.has_permission('enrollments.write') then
    raise exception 'not permitted to withdraw a learner' using errcode = '42501';
  end if;
  if p_kind not in ('transferred_out', 'dropped') then
    raise exception 'A withdrawal is either transferred_out or dropped.'
      using errcode = '23514';
  end if;
  -- A reason is not optional. "Why did this learner leave" is the one
  -- question the record exists to answer, and a blank is not an answer.
  if nullif(btrim(coalesce(p_reason, '')), '') is null then
    raise exception 'A reason is required to withdraw a learner.'
      using errcode = '23514';
  end if;

  select * into v_e from public.enrollments e
   where e.id = p_enrollment_id and e.school_id = v_school;
  if v_e.id is null then
    raise exception 'enrolment not found' using errcode = 'P0002';
  end if;
  if v_e.status in ('transferred_out', 'dropped') then
    raise exception 'This enrolment is already closed (%).', v_e.status
      using errcode = '23505';
  end if;

  v_n := app.drop_class_enrolments(p_enrollment_id, null, 'dropped', v_eff);

  update public.enrollments
     set status = p_kind,
         remarks = coalesce(nullif(btrim(p_destination), ''), remarks),
         updated_at = now()
   where id = p_enrollment_id;

  perform app.record_enrollment_event(
    p_enrollment_id,
    case when p_kind = 'transferred_out' then 'transfer_out' else 'drop' end,
    v_eff, v_e.status, p_kind, null, null,
    case when nullif(btrim(coalesce(p_destination, '')), '') is null then p_reason
         else p_reason || ' — to ' || btrim(p_destination) end);

  perform app.write_audit('enrollments.withdraw', 'enrollments', p_enrollment_id,
    jsonb_build_object('status', v_e.status),
    jsonb_build_object('status', p_kind, 'effectiveDate', v_eff,
                       'destination', p_destination),
    p_reason);

  -- The PERSON is not withdrawn — only this year's enrolment. A learner
  -- who transfers out in October and returns in January is the same
  -- student record with a re-entry event, not a new one.
  return jsonb_build_object('status', p_kind, 'classesClosed', v_n);
end;
$fn$;

-- ------------------------------------------------------------
-- 6. public.reenrol_student — they came back
-- ------------------------------------------------------------
create or replace function public.reenrol_student(
  p_enrollment_id  uuid,
  p_effective_date date default null,
  p_reason         text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_school uuid := app.current_school_id();
  v_e      public.enrollments;
  v_eff    date := coalesce(p_effective_date, current_date);
  v_added  int := 0;
  v_class  uuid;
begin
  if not app.has_permission('enrollments.write') then
    raise exception 'not permitted to re-enrol a learner' using errcode = '42501';
  end if;

  select * into v_e from public.enrollments e
   where e.id = p_enrollment_id and e.school_id = v_school;
  if v_e.id is null then
    raise exception 'enrolment not found' using errcode = 'P0002';
  end if;
  if v_e.status not in ('transferred_out', 'dropped') then
    raise exception 'This enrolment is not closed, so there is nothing to re-open.'
      using errcode = '23505';
  end if;

  update public.enrollments
     set status = 'enrolled', updated_at = now()
   where id = p_enrollment_id;

  -- Rejoin the current section's classes. REACTIVATE first: the rows
  -- closed on withdrawal are the learner's membership, marks and all,
  -- and `sync_class_roster` would skip straight past them on its unique
  -- constraint. Then sync, for any class created while they were away.
  if v_e.section_id is not null then
    v_added := app.reactivate_class_enrolments(p_enrollment_id, v_e.section_id);
    for v_class in
      select cl.id from public.classes cl
      where cl.school_id = v_school and cl.section_id = v_e.section_id
        and cl.academic_year_id = v_e.academic_year_id and cl.status = 'active'
    loop
      v_added := v_added + coalesce(public.sync_class_roster(v_class), 0);
    end loop;
  end if;

  perform app.record_enrollment_event(
    p_enrollment_id, 're_entry', v_eff, v_e.status, 'enrolled', null, null, p_reason);

  perform app.write_audit('enrollments.reenrol', 'enrollments', p_enrollment_id,
    jsonb_build_object('status', v_e.status),
    jsonb_build_object('status', 'enrolled', 'effectiveDate', v_eff), p_reason);

  return jsonb_build_object('status', 'enrolled', 'classesRejoined', v_added);
end;
$fn$;

-- ------------------------------------------------------------
-- 7. The existing writers start recording events too
-- ------------------------------------------------------------
-- enrol_student and admit_student have written enrolments since 0025
-- without an event. Derived from 0025 verbatim; the only additions are
-- the event calls and, in admit_student, the namesake guard.

create or replace function public.enrol_student(
  p_student_id uuid,
  p_enrollment jsonb
) returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_school uuid := app.current_school_id();
  v_id     uuid;
  v_year   uuid := (p_enrollment ->> 'academicYearId')::uuid;
  v_grade  uuid := (p_enrollment ->> 'gradeLevelId')::uuid;
  v_sec    uuid := (nullif(p_enrollment ->> 'sectionId', ''))::uuid;
  v_status text := coalesce(nullif(btrim(p_enrollment ->> 'status'), ''), 'enrolled');
  v_date   date := coalesce((nullif(p_enrollment ->> 'dateEnrolled', ''))::date, current_date);
  v_class  uuid;
begin
  if not app.has_permission('enrollments.write') then
    raise exception 'not permitted to enrol learners' using errcode = '42501';
  end if;
  if v_year is null or v_grade is null then
    raise exception 'an academic year and a grade level are required' using errcode = '23514';
  end if;
  if not exists (select 1 from public.students st
                 where st.id = p_student_id and st.school_id = v_school) then
    raise exception 'learner not found in this school' using errcode = 'P0002';
  end if;

  if exists (select 1 from public.enrollments e
             where e.student_id = p_student_id and e.academic_year_id = v_year) then
    raise exception
      'this learner is already enrolled for that school year — edit the enrolment instead of adding one'
      using errcode = '23505';
  end if;

  insert into public.enrollments (
    school_id, student_id, academic_year_id, grade_level_id, section_id,
    date_enrolled, status, previous_school, remarks
  ) values (
    v_school, p_student_id, v_year, v_grade, v_sec, v_date,
    -- 'enrolled', not 'active': enrollments.status is a DepEd enrolment
    -- state, not a generic row flag. students.status is the one that
    -- uses 'active'.
    v_status,
    nullif(btrim(p_enrollment ->> 'previousSchool'), ''),
    nullif(btrim(p_enrollment ->> 'remarks'), '')
  )
  returning id into v_id;

  -- The enrolment itself is an event. Without it the history starts at
  -- the first transfer, which reads as though the learner materialised
  -- mid-year.
  perform app.record_enrollment_event(
    v_id,
    case when v_status = 'transferred_in' then 'transfer_in' else 'enrolled' end,
    v_date, null,
    (select gl.name from public.grade_levels gl where gl.id = v_grade),
    null, v_grade,
    nullif(btrim(p_enrollment ->> 'previousSchool'), ''));

  if v_sec is not null then
    perform app.record_enrollment_event(
      v_id, 'section_change', v_date, null,
      (select sec.name from public.sections sec where sec.id = v_sec),
      null, v_sec, 'Assigned at enrolment');

    -- ── A BUG THIS PHASE FOUND, NOT ONE IT INTRODUCED ──────────────
    --
    -- `sync_class_roster` was called only from `create_class`, so a
    -- roster was filled once, when the class was made. A learner
    -- enrolled into Pearl AFTERWARDS joined nothing: the registrar's
    -- screen showed them in Pearl, and all four of Pearl's teachers had
    -- a gradebook without them. Nothing errored, and the learner would
    -- have been discovered missing at the end of a term.
    --
    -- Verified against the seed: enrolling into Pearl, which has two
    -- classes, produced zero class enrolments before this line.
    for v_class in
      select cl.id from public.classes cl
      where cl.school_id = v_school and cl.section_id = v_sec
        and cl.academic_year_id = v_year and cl.status = 'active'
    loop
      perform public.sync_class_roster(v_class);
    end loop;
  end if;

  perform app.write_audit('enrollments.create', 'enrollments', v_id, null, p_enrollment);
  return v_id;
end;
$$;

-- update_enrollment keeps working exactly as before, and now records an
-- event when it moves a section or a grade level. It stays the general
-- editor — the dedicated RPCs above are for the acts that need a reason
-- and a roster consequence.
create or replace function public.update_enrollment(
  p_enrollment_id uuid,
  p_patch         jsonb
) returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_before jsonb;
  v_e      public.enrollments;
  v_gnew   uuid;
  v_snew   uuid;
  v_class  uuid;
begin
  if not app.has_permission('enrollments.write') then
    raise exception 'not permitted to edit enrolments' using errcode = '42501';
  end if;

  select * into v_e from public.enrollments e
  where e.id = p_enrollment_id and e.school_id = app.current_school_id();
  if v_e.id is null then
    raise exception 'enrolment not found' using errcode = 'P0002';
  end if;
  v_before := to_jsonb(v_e);

  update public.enrollments set
    grade_level_id   = coalesce((nullif(p_patch ->> 'gradeLevelId', ''))::uuid, grade_level_id),
    section_id       = case when p_patch ? 'sectionId'       then (nullif(p_patch ->> 'sectionId', ''))::uuid else section_id end,
    status           = coalesce(nullif(btrim(p_patch ->> 'status'), ''), status),
    promotion_status = case when p_patch ? 'promotionStatus' then nullif(btrim(p_patch ->> 'promotionStatus'), '') else promotion_status end,
    previous_school  = case when p_patch ? 'previousSchool'  then nullif(btrim(p_patch ->> 'previousSchool'), '')  else previous_school end,
    remarks          = case when p_patch ? 'remarks'         then nullif(btrim(p_patch ->> 'remarks'), '')         else remarks end,
    updated_at       = now()
  where id = p_enrollment_id
  returning grade_level_id, section_id into v_gnew, v_snew;

  if v_gnew is distinct from v_e.grade_level_id then
    perform app.record_enrollment_event(
      p_enrollment_id, 'grade_level_change', current_date,
      (select gl.name from public.grade_levels gl where gl.id = v_e.grade_level_id),
      (select gl.name from public.grade_levels gl where gl.id = v_gnew),
      v_e.grade_level_id, v_gnew, 'Corrected on the enrolment');
  end if;

  if v_snew is distinct from v_e.section_id then
    perform app.record_enrollment_event(
      p_enrollment_id, 'section_change', current_date,
      (select sec.name from public.sections sec where sec.id = v_e.section_id),
      (select sec.name from public.sections sec where sec.id = v_snew),
      v_e.section_id, v_snew, 'Changed on the enrolment');

    -- The rosters move too. Without this, editing the section here
    -- would be a way around `transfer_student_section` that leaves the
    -- learner on their old teachers' gradebooks — the same defect, one
    -- screen over. The dedicated RPC still exists because it requires a
    -- reason and reports what moved; this is the safety net under the
    -- general editor.
    if v_e.section_id is not null then
      perform app.drop_class_enrolments(
        p_enrollment_id, v_e.section_id, 'transferred', current_date);
    end if;
    if v_snew is not null then
      for v_class in
        select cl.id from public.classes cl
        where cl.school_id = app.current_school_id() and cl.section_id = v_snew
          and cl.academic_year_id = v_e.academic_year_id and cl.status = 'active'
      loop
        perform public.sync_class_roster(v_class);
      end loop;
    end if;
  end if;

  perform app.write_audit('enrollments.update', 'enrollments', p_enrollment_id, v_before, p_patch);
end;
$$;

-- ------------------------------------------------------------
-- 8. The namesake guard on admit_student
-- ------------------------------------------------------------
-- 0025 refuses a duplicate LRN or student number and names the clash.
-- It says nothing about two "Juan Dela Cruz" records with no LRN
-- between them, which is how a school ends up with one learner twice.
--
-- WARN, NEVER REFUSE. Real namesakes exist and real siblings share
-- surnames; a hard block would leave a registrar unable to admit a real
-- learner. Same shape as correct_learner_name's confirmation (0034).
create or replace function public.admit_student(
  p_student          jsonb,
  p_enrollment       jsonb,
  p_confirm_namesake boolean default false
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_school     uuid := app.current_school_id();
  v_student_id uuid;
  v_enrol_id   uuid;
  v_lrn        text := nullif(btrim(p_student ->> 'lrn'), '');
  v_number     text := nullif(btrim(p_student ->> 'studentNumber'), '');
  v_existing   uuid;
  v_first      text := btrim(coalesce(p_student ->> 'firstName', ''));
  v_last       text := btrim(coalesce(p_student ->> 'lastName', ''));
  v_birth      date := (nullif(p_student ->> 'birthDate', ''))::date;
  v_twins      jsonb;
begin
  if not app.has_permission('students.write') then
    raise exception 'not permitted to add learners' using errcode = '42501';
  end if;
  if v_school is null then
    raise exception 'no school in session' using errcode = '42501';
  end if;

  if nullif(btrim(p_student ->> 'lastName'), '') is null
     or nullif(btrim(p_student ->> 'firstName'), '') is null then
    raise exception 'a first name and a last name are required' using errcode = '23514';
  end if;

  -- Refuse a duplicate BEFORE writing, and say who it already is. The
  -- unique index would also catch this, but "duplicate key value
  -- violates unique constraint students_lrn_unique" is not something to
  -- show a registrar.
  select st.id into v_existing
  from public.students st
  where st.school_id = v_school and st.deleted_at is null
    and ((v_lrn    is not null and st.lrn = v_lrn)
      or (v_number is not null and st.student_number = v_number));

  if v_existing is not null then
    raise exception
      'a learner with that % already exists in this school (%)',
      case when v_lrn is not null and exists (
        select 1 from public.students where id = v_existing and lrn = v_lrn
      ) then 'LRN' else 'student number' end,
      (select public.student_display_name(s.*) from public.students s where s.id = v_existing)
      using errcode = '23505';
  end if;

  -- ── ADDED BY 0041: the namesake warning ───────────────────────────
  --
  -- WARN, NEVER REFUSE. An identifier clash above is a certainty and
  -- raises. A name clash is a SUSPICION: real namesakes exist, siblings
  -- share surnames, and a hard block would leave a registrar unable to
  -- admit a real learner who happens to share a name with one already
  -- here. So this RETURNS rather than raising, carrying the candidates
  -- so the registrar can look at them and decide.
  --
  -- Returning is deliberate: an exception rolls the statement back and
  -- carries only a string, and the caller would have to parse a message
  -- to show a comparison. A status the caller reads is a contract.
  if not coalesce(p_confirm_namesake, false) then
    select jsonb_agg(jsonb_build_object(
             'studentId',     st.id,
             'displayName',   public.student_display_name(st.*),
             'lrn',           st.lrn,
             'studentNumber', st.student_number,
             'birthDate',     st.birth_date))
      into v_twins
    from public.students st
    where st.school_id = v_school and st.deleted_at is null
      and app.normalise_name(st.first_name) = app.normalise_name(v_first)
      and app.normalise_name(st.last_name)  = app.normalise_name(v_last)
      -- A birth date NARROWS the match when both sides have one. When
      -- either is missing the name alone still warrants a warning —
      -- most schools admit learners without a birth date on the form.
      and (v_birth is null or st.birth_date is null or st.birth_date = v_birth);

    if v_twins is not null then
      return jsonb_build_object(
        'status',  'needs_confirmation',
        'reason',  'namesake',
        'message',
          'This school already has a learner by that name. Check the record '
          || 'below before adding a second one — if this is a different '
          || 'person, confirm and continue.',
        'matches', v_twins);
    end if;
  end if;

  insert into public.students (
    school_id, student_number, lrn,
    first_name, middle_name, last_name, suffix,
    sex, birth_date, birth_place, mother_tongue, religion,
    address_line, barangay, municipality, province,
    contact_number, email, status
  ) values (
    v_school, v_number, v_lrn,
    btrim(p_student ->> 'firstName'),
    nullif(btrim(p_student ->> 'middleName'), ''),
    btrim(p_student ->> 'lastName'),
    nullif(btrim(p_student ->> 'suffix'), ''),
    nullif(btrim(p_student ->> 'sex'), ''),
    (nullif(p_student ->> 'birthDate', ''))::date,
    nullif(btrim(p_student ->> 'birthPlace'), ''),
    nullif(btrim(p_student ->> 'motherTongue'), ''),
    nullif(btrim(p_student ->> 'religion'), ''),
    nullif(btrim(p_student ->> 'addressLine'), ''),
    nullif(btrim(p_student ->> 'barangay'), ''),
    nullif(btrim(p_student ->> 'municipality'), ''),
    nullif(btrim(p_student ->> 'province'), ''),
    nullif(btrim(p_student ->> 'contactNumber'), ''),
    nullif(btrim(p_student ->> 'email'), ''),
    coalesce(nullif(btrim(p_student ->> 'status'), ''), 'active')
  )
  returning id into v_student_id;

  -- ── CHANGED BY 0041: enrolling is now optional ────────────────────
  --
  -- 0025 always enrolled, which made "add a learner" and "place a
  -- learner" one act. They are not: a registrar often has the person
  -- before the section is decided. An enrolment block naming an
  -- academic year still enrols exactly as before, so every existing
  -- caller is unaffected.
  if p_enrollment is not null
     and p_enrollment <> 'null'::jsonb
     and nullif(btrim(p_enrollment ->> 'academicYearId'), '') is not null then
    v_enrol_id := public.enrol_student(v_student_id, p_enrollment);
  end if;

  perform app.write_audit('students.create', 'students', v_student_id, null,
    jsonb_build_object('lrn', v_lrn, 'studentNumber', v_number,
                       'confirmedNamesake', coalesce(p_confirm_namesake, false)));

  -- 'status' is additive: every existing caller reads studentId and
  -- enrollmentId and keeps working.
  return jsonb_build_object(
    'status', 'created',
    'studentId', v_student_id, 'enrollmentId', v_enrol_id);
end;
$$;

-- 0025's two-argument form would otherwise stay callable beside the new
-- one, and a two-argument call would be ambiguous between them.
drop function if exists public.admit_student(jsonb, jsonb);

comment on function public.admit_student is
  'Adds a learner and, optionally, their enrolment. Refuses a duplicate '
  'LRN or student number outright; WARNS about a namesake and proceeds '
  'only when the registrar confirms it is a different person.';

-- ------------------------------------------------------------
-- 8b. The import already asks. Do not ask it again.
-- ------------------------------------------------------------
-- `import_commit` calls admit_student for every learner the person
-- reviewing the import marked 'create'. That IS the confirmation — the
-- Import Center shows each workbook name beside its candidate matches
-- and the person chooses. Leaving the new guard on would make
-- admit_student return `needs_confirmation` inside the commit loop,
-- `->> 'enrollmentId'` would be null, and the learner would be SILENTLY
-- DROPPED from the roster with the import still reporting success.
--
-- Derived from 0026 verbatim; the only change is the third argument.
create or replace function public.import_commit(p_plan jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_school    uuid := app.current_school_id();
  v_class     uuid := nullif(p_plan ->> 'classId', '')::uuid;
  v_year      uuid := nullif(p_plan ->> 'academicYearId', '')::uuid;
  v_section   uuid := nullif(p_plan ->> 'sectionId', '')::uuid;
  v_subject   uuid := nullif(p_plan ->> 'subjectId', '')::uuid;
  v_grade     uuid := nullif(p_plan ->> 'gradeLevelId', '')::uuid;
  v_teacher   uuid := nullif(p_plan ->> 'teacherId', '')::uuid;
  v_file      text := coalesce(nullif(p_plan ->> 'fileName', ''), 'workbook.xlsx');
  v_created_class boolean := false;
  v_students  int := 0;
  v_enrolled  int := 0;
  v_assess    int := 0;
  v_marks     int := 0;
  v_batch     uuid;
  r           record;
  v_enrol     uuid;
  -- workbook row -> enrolment id, filled in as learners are resolved
  v_rows      jsonb := '{}'::jsonb;
begin
  if not app.has_permission('imports.execute') then
    raise exception 'not permitted to run imports' using errcode = '42501';
  end if;

  -- ---------- the class ----------
  if v_class is null then
    if v_year is null or v_section is null or v_subject is null then
      raise exception 'the plan does not resolve a class' using errcode = '22023';
    end if;
    if not app.has_permission('classes.assign') then
      raise exception
        'this workbook is for a class that does not exist yet, and your account '
        'cannot create classes. Ask the registrar to create it, then import again'
        using errcode = '42501';
    end if;

    -- ON CONFLICT, not a pre-check: two imports racing must produce one
    -- class, and the unique constraint is the only thing that can
    -- guarantee that. This is also why re-importing cannot duplicate.
    insert into public.classes
      (school_id, academic_year_id, section_id, subject_id, primary_teacher_id)
    values (v_school, v_year, v_section, v_subject, v_teacher)
    on conflict (academic_year_id, section_id, subject_id) do nothing
    returning id into v_class;

    if v_class is null then
      select cl.id into v_class from public.classes cl
      where cl.academic_year_id = v_year and cl.section_id = v_section
        and cl.subject_id = v_subject;
    else
      v_created_class := true;
    end if;
  else
    select cl.school_id, cl.section_id, cl.academic_year_id
      into v_school, v_section, v_year
    from public.classes cl where cl.id = v_class;
    if v_school is distinct from app.current_school_id() then
      raise exception 'class not found' using errcode = 'P0002';
    end if;
  end if;

  if not (app.teaches_class(v_class) or app.has_permission('classes.assign')) then
    raise exception 'you do not teach this class' using errcode = '42501';
  end if;

  -- A learner created by this import is enrolled into the section the
  -- class belongs to, so the grade level comes from the section rather
  -- than being trusted from the plan.
  if v_grade is null and v_section is not null then
    select s.grade_level_id into v_grade
    from public.sections s where s.id = v_section;
  end if;

  -- ---------- learners ----------
  -- Two actions only, both decided in the preview: `link` an existing
  -- enrolment, or `create` a learner the school does not have. There is
  -- no third action, and in particular no matching.
  -- ⚠️ Marks reference the WORKBOOK ROW, not an enrolment id, and this
  -- loop is what makes that possible. A learner being created has no
  -- enrolment id at the moment the plan is written, so a plan that
  -- keyed marks by enrolment id would silently drop every mark
  -- belonging to a new learner — the rows would simply fail to join.
  -- The row number is the only identifier the workbook has, and it is
  -- the one thing that is stable from the file all the way to here.
  for r in
    select
      x ->> 'action'                        as action,
      x ->> 'row'                           as row_key,
      nullif(x ->> 'enrollmentId', '')::uuid as enrollment_id,
      x -> 'student'                        as student
    from jsonb_array_elements(coalesce(p_plan -> 'learners', '[]'::jsonb)) x
  loop
    v_enrol := null;
    if r.action = 'create' then
      if not (app.has_permission('students.write')
              and app.has_permission('enrollments.write')) then
        raise exception
          'this workbook contains learners the school does not have, and your '
          'account cannot create learners. Ask the registrar to admit them first'
          using errcode = '42501';
      end if;
      -- The third argument is 0041's. The person running the import
      -- has already been shown this learner beside every candidate
      -- match and chose 'create', so asking again here would strand
      -- them off the roster while the import reported success.
      select (public.admit_student(
                r.student,
                jsonb_build_object('academicYearId', v_year,
                                   'gradeLevelId',   v_grade,
                                   'sectionId',      v_section),
                true
              ) ->> 'enrollmentId')::uuid
        into v_enrol;
      v_students := v_students + 1;
    elsif r.action = 'link' then
      v_enrol := r.enrollment_id;
    else
      continue;
    end if;

    if v_enrol is not null then
      insert into public.class_enrollments (school_id, class_id, enrollment_id)
      values (v_school, v_class, v_enrol)
      on conflict (class_id, enrollment_id) do nothing;
      v_enrolled := v_enrolled + 1;
      if r.row_key is not null then
        v_rows := v_rows || jsonb_build_object(r.row_key, v_enrol);
      end if;
    end if;
  end loop;

  -- ---------- assessments and marks, per period ----------
  -- Delegated to save_assessments and save_scores rather than
  -- reimplemented. Those functions already refuse a period that has
  -- left the teacher's hands, already refuse to delete an assessment
  -- that carries marks, and already carry the audit write. An import
  -- that wrote its own upserts would be a second set of rules for the
  -- same act, and the two would drift.
  for r in
    select
      nullif(x ->> 'periodId', '')::uuid as period_id,
      coalesce(x -> 'assessments', '[]'::jsonb) as assessments,
      coalesce(x -> 'marks', '[]'::jsonb)       as marks
    from jsonb_array_elements(coalesce(p_plan -> 'periods', '[]'::jsonb)) x
  loop
    if r.period_id is null then continue; end if;

    -- ⚠️ THIS FUNCTION IS SECURITY DEFINER, SO RLS IS NOT ENFORCING
    -- ANYTHING BELOW. save_scores relies entirely on the
    -- assessment_scores policies for both permission and editability,
    -- and those policies do not run for the definer. Without these two
    -- checks an import could write marks into a period the registrar
    -- already holds — the one thing the whole chain of custody exists
    -- to prevent. save_assessments raises on its own, but it is checked
    -- here too so the refusal happens before any period is touched.
    if not (app.has_permission('grades.encode')
            and app.has_permission('assessments.write')) then
      raise exception 'your account cannot record marks' using errcode = '42501';
    end if;

    if not app.submission_is_editable(v_class, r.period_id) then
      raise exception
        'that grading period has already been submitted, so it cannot be '
        'overwritten by an import. Take the record back first'
        using errcode = '42501';
    end if;

    -- save_assessments treats its payload as the COMPLETE set for the
    -- period and removes anything absent. The plan therefore carries
    -- every assessment the period should end up with, existing ones
    -- included, and the preview shows exactly that set.
    v_assess := v_assess + coalesce(
      (public.save_assessments(v_class, r.period_id, r.assessments) ->> 'written')::int, 0);

    -- Marks reference assessments by their natural key, because a
    -- brand-new assessment has no id until the line above ran.
    v_marks := v_marks + coalesce((
      public.save_scores((
        select coalesce(jsonb_agg(jsonb_build_object(
                 'assessmentId',      a.id,
                 'classEnrollmentId', ce.id,
                 'raw',               m ->> 'raw')), '[]'::jsonb)
        from jsonb_array_elements(r.marks) m
        join public.assessments a
          on a.class_id = v_class
         and a.academic_period_id = r.period_id
         and a.grade_component_id = (m ->> 'componentId')::uuid
         and a.ordinal = (m ->> 'ordinal')::int
        join public.class_enrollments ce
          on ce.class_id = v_class
         and ce.enrollment_id = (v_rows ->> (m ->> 'row'))::uuid
      )) ->> 'written')::int, 0);
  end loop;

  insert into public.import_batches
    (school_id, import_type, filename, class_id, status,
     row_count, success_count, error_count, report, uploaded_by)
  values (
    v_school, 'three_term_class_record', v_file, v_class, 'committed',
    v_marks, v_marks, 0,
    jsonb_build_object(
      'createdClass', v_created_class,
      'studentsCreated', v_students,
      'learnersOnRoster', v_enrolled,
      'assessments', v_assess,
      'marks', v_marks),
    app.current_user_id())
  returning id into v_batch;

  perform app.write_audit(
    'import.commit', 'classes', v_class, null,
    jsonb_build_object('batchId', v_batch, 'fileName', v_file,
                       'createdClass', v_created_class,
                       'studentsCreated', v_students,
                       'assessments', v_assess, 'marks', v_marks));

  return jsonb_build_object(
    'batchId', v_batch,
    'classId', v_class,
    'createdClass', v_created_class,
    'studentsCreated', v_students,
    'learnersOnRoster', v_enrolled,
    'assessments', v_assess,
    'marks', v_marks);
end;
$fn$;

-- ------------------------------------------------------------
-- 9. rds.enrollment_history — the record, for a screen
-- ------------------------------------------------------------
-- SECURITY INVOKER: the RLS policies on enrollment_events decide who
-- may read it, exactly as student_profile does.
create or replace function rds.enrollment_history(p_student_id uuid)
returns jsonb
language sql
stable
set search_path = public, pg_temp
as $fn$
  -- event_date is what a reader cares about; `seq` breaks the ties that
  -- created_at cannot, because two events written in one transaction
  -- share it exactly.
  select coalesce(jsonb_agg(x order by x ->> 'eventDate' desc, (x ->> 'seq')::bigint desc), '[]'::jsonb)
  from (
    select jsonb_build_object(
      'id',           ev.id,
      'enrollmentId', ev.enrollment_id,
      'academicYear', ay.label,
      'eventType',    ev.event_type,
      'eventDate',    ev.event_date,
      'from',         ev.from_value,
      'to',           ev.to_value,
      'notes',        ev.notes,
      'recordedAt',   ev.created_at,
      'seq',          ev.seq,
      'recordedBy',   nullif(concat_ws(', ', u.last_name, u.first_name), '')
    ) as x
    from public.enrollment_events ev
    join public.enrollments e on e.id = ev.enrollment_id
    join public.academic_years ay on ay.id = e.academic_year_id
    left join public.users u on u.id = ev.recorded_by
    where e.student_id = p_student_id
  ) rows
$fn$;

create or replace function public.enrollment_history(p_student_id uuid)
returns jsonb language sql stable set search_path = public, pg_temp
as $fn$ select rds.enrollment_history(p_student_id) $fn$;

-- ------------------------------------------------------------
-- 10. Grants — and the revoke that 0038 and 0040 forgot
-- ------------------------------------------------------------
grant execute on function
  public.transfer_student_section(uuid, uuid, date, text),
  public.withdraw_student(uuid, text, date, text, text),
  public.reenrol_student(uuid, date, text),
  public.admit_student(jsonb, jsonb, boolean),
  rds.enrollment_history(uuid),
  public.enrollment_history(uuid)
to authenticated;

revoke execute on function
  public.transfer_student_section(uuid, uuid, date, text),
  public.withdraw_student(uuid, text, date, text, text),
  public.reenrol_student(uuid, date, text),
  public.admit_student(jsonb, jsonb, boolean),
  rds.enrollment_history(uuid),
  public.enrollment_history(uuid)
from public, anon;

-- The Phase 0 audit found three functions from 0038 and 0040 reachable
-- by `anon`: Postgres grants EXECUTE to PUBLIC by default, migration
-- 0017 revoked it from everything that existed THEN, and the two later
-- migrations did not repeat it. They fail closed on has_permission, so
-- nothing was exposed — but the posture is deliberate and this restores
-- it. Any migration that creates a public. function must do the same.
-- app.* helpers are not part of the client surface at all.
revoke execute on function
  app.record_enrollment_event(uuid, text, date, text, text, uuid, uuid, text),
  app.drop_class_enrolments(uuid, uuid, text, date),
  app.reactivate_class_enrolments(uuid, uuid)
from public, anon, authenticated;

revoke execute on function
  public.create_subject(text, text, uuid, numeric, uuid, uuid[]),
  public.set_subject_active(uuid, boolean),
  public.set_subject_grade_levels(uuid, uuid, uuid[]),
  public.subject_catalogue(uuid)
from public, anon;

commit;
